/**
 * AI-2201 (e2e) — the bug reproduction end to end: a proposal generated by the
 * real C3 engine, persisted through the real adapter into the real wired store,
 * and listed via `GET /admin/api/proposals` must come back in the *flat* shape
 * the console SPA normalizer reads — not the nested `ProposalRow` that rendered
 * every card as `(untitled proposal)` with a `0/0` diff stat.
 *
 * Before the fix the route returned `store.list()` (nested `proposal.*`), so
 * `title`/`workflowId`/`diffs`/`evidence` were all undefined on the wire.
 */
import request from "supertest";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { createApp } from "../index.js";
import { reloadAgents } from "../agents.js";
import {
  generateProposals,
  type FailureCluster,
  type GenerationContext,
} from "./proposal-generator.js";
import { persistGeneratedProposals } from "./generated-proposal-adapter.js";

const ADMIN_SECRET = "ai2201-secret";
const guidanceRel = path.join("workflows", "dev-impl", "write-tests.md");

function git(cwd: string, args: string[]): void {
  execFileSync("git", args, { cwd });
}

describe("AI-2201 GET /admin/api/proposals flat shape", () => {
  let dir: string;
  let configRoot: string;
  let appState: ReturnType<typeof createApp>;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "ai2201-e2e-"));

    const webDist = path.join(dir, "web-dist");
    fs.mkdirSync(webDist, { recursive: true });
    fs.writeFileSync(path.join(webDist, "index.html"), '<!doctype html><div id="root"></div>', "utf8");
    const agentsFile = path.join(dir, "agents.json");
    fs.writeFileSync(agentsFile, JSON.stringify({ agents: [] }), "utf8");

    configRoot = path.join(dir, "config");
    fs.mkdirSync(path.join(configRoot, "workflows", "dev-impl"), { recursive: true });
    fs.writeFileSync(
      path.join(configRoot, guidanceRel),
      "# write-tests\n\nWrite failing tests covering every in-scope AC before implementation.\n",
      "utf8",
    );
    git(configRoot, ["init", "-q"]);
    git(configRoot, ["config", "user.email", "igor@fancymatt.local"]);
    git(configRoot, ["config", "user.name", "igor"]);
    git(configRoot, ["add", "-A"]);
    git(configRoot, ["commit", "-q", "-m", "seed"]);

    process.env.AGENTS_FILE = agentsFile;
    process.env.ADMIN_SECRET = ADMIN_SECRET;
    process.env.ADMIN_WEB_DIST = webDist;
    process.env.LINEAR_CONNECTOR_CONFIG_DIR = configRoot;
    reloadAgents();

    appState = createApp({
      proposalsDbPath: path.join(dir, "proposals.db"),
      bagDbPath: path.join(dir, "bag.db"),
      agentQueueDbPath: path.join(dir, "queue.db"),
      operationalEventsDbPath: path.join(dir, "opevents.db"),
      observationsDbPath: path.join(dir, "obs.db"),
    });
  });

  afterEach(() => {
    delete process.env.AGENTS_FILE;
    delete process.env.ADMIN_SECRET;
    delete process.env.ADMIN_WEB_DIST;
    delete process.env.LINEAR_CONNECTOR_CONFIG_DIR;
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it("returns flat, renderable fields (no untitled/empty cards)", async () => {
    const ctx: GenerationContext = {
      readSurfaces: (workflowId, stateId) => {
        if (workflowId !== "dev-impl" || stateId !== "write-tests") return [];
        return [
          {
            kind: "guidance",
            path: guidanceRel,
            content: fs.readFileSync(path.join(configRoot, guidanceRel), "utf8"),
          },
        ];
      },
    };
    const clusters: FailureCluster[] = [
      {
        workflow: "dev-impl",
        step: "write-tests",
        reasonCode: "missing-tests",
        count: 5,
        exceedsThreshold: true,
        ticketIds: ["AI-2041-SYNTH-1", "AI-2041-SYNTH-2", "AI-2041-SYNTH-3", "AI-2041-SYNTH-4", "AI-2041-SYNTH-5"],
      },
    ];

    const generated = generateProposals(clusters, ctx);
    expect(generated).toHaveLength(1);
    const key = generated[0].idempotencyKey;
    persistGeneratedProposals(appState.proposalStore, generated);

    const res = await request(appState.app).get("/admin/api/proposals").set("x-admin-secret", ADMIN_SECRET);
    expect(res.status).toBe(200);

    const proposals = res.body.proposals as Array<Record<string, unknown>>;
    const p = proposals.find((x) => x.id === key)!;
    expect(p).toBeDefined();

    // The flat fields the SPA normalizer reads — all present at the top level.
    expect(p.title).not.toBe("(untitled proposal)");
    expect(p.workflowId).toBe("dev-impl");
    expect(p.stateId).toBe("write-tests");
    expect(p.confidenceScore).toBe(generated[0].confidenceScore);
    expect(p.failureCount).toBe(5);
    expect(p.severity).toBe("MEDIUM");
    expect(Array.isArray(p.diffs)).toBe(true);
    expect((p.diffs as unknown[]).length).toBeGreaterThan(0);
    expect(p.diffStat).not.toEqual({ added: 0, removed: 0 });
    expect((p.evidence as unknown[]).length).toBeGreaterThan(0);
    // The nested `proposal` blob should NOT leak onto the console wire shape.
    expect(p.proposal).toBeUndefined();
  });
});
