/**
 * AI-2038 (P4-C3) — Proposal store: status-queryable persistence + in-place revision.
 *
 * Follows src/store/observation-store.ts (better-sqlite3, WAL, private migrate(),
 * snake_case columns / camelCase TS). Proposals generated by proposal-generator.ts
 * persist here for human review.
 *
 * AC3.3 — proposals persist in a store queryable by status:
 *         pending / approved / rejected / applied / apply-failed / in-revision.
 * AC3.4 — revise: operator feedback attaches to the proposal; regeneration
 *         updates the proposal IN PLACE, preserving revision history
 *         (UX decision #3). The record always holds the CURRENT version; the
 *         superseded version's targets + the feedback that superseded it are
 *         pushed onto an immutable `revisions[]` thread.
 *
 * The `targets[]` core round-trips through SQLite as JSON. Lifecycle fields
 * (id/status/createdAt/updatedAt/revisions) live only on the stored record — the
 * deterministic core (proposal-generator.ts) carries none of them (AC3.2).
 */

import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";
import { componentLogger, createLogger } from "../logger.js";
import {
  computeIdempotencyKey as _computeIdempotencyKey,
  type GeneratedProposal,
  type ProposalTarget,
} from "./proposal-generator.js";

const log = componentLogger(createLogger(process.env.LOG_LEVEL ?? "info"), "proposal-store");

/** The six lifecycle statuses a stored proposal may hold (AC3.3). */
export const PROPOSAL_STATUSES = [
  "pending",
  "approved",
  "rejected",
  "applied",
  "apply-failed",
  "in-revision",
] as const;

export type ProposalStatus = (typeof PROPOSAL_STATUSES)[number];

function isProposalStatus(value: string): value is ProposalStatus {
  return (PROPOSAL_STATUSES as readonly string[]).includes(value);
}

/** One entry in a proposal's immutable revision thread. */
export interface ProposalRevision {
  /** The superseded version this entry preserves. */
  version: number;
  /** The operator ask that superseded it. */
  feedback: string;
  /** The superseded version's regenerated targets. */
  targets: ProposalTarget[];
  idempotencyKey: string;
  createdAt: string;
}

/** A persisted proposal record — the deterministic core plus lifecycle fields. */
export interface ProposalRecord extends GeneratedProposal {
  id: number;
  status: ProposalStatus;
  createdAt: string;
  updatedAt: string;
  revisions: ProposalRevision[];
}

export class ProposalStore {
  private db: Database.Database;

  constructor(dbPath?: string) {
    const resolvedPath =
      dbPath ??
      path.join(process.env.DATA_DIR ?? path.join(process.cwd(), "data"), "proposals.db");
    const dir = path.dirname(resolvedPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    this.db = new Database(resolvedPath);
    this.db.pragma("journal_mode = WAL");
    this.migrate();
  }

  private migrate(): void {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS proposals (
        id               INTEGER PRIMARY KEY AUTOINCREMENT,
        workflow_id      TEXT    NOT NULL,
        state_id         TEXT    NOT NULL,
        targets          TEXT    NOT NULL,
        confidence_score REAL    NOT NULL,
        evidence_cluster TEXT    NOT NULL,
        failure_count    INTEGER NOT NULL,
        version          INTEGER NOT NULL,
        idempotency_key  TEXT    NOT NULL,
        status           TEXT    NOT NULL DEFAULT 'pending',
        revisions        TEXT    NOT NULL DEFAULT '[]',
        created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
        updated_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
      );
      CREATE INDEX IF NOT EXISTS idx_proposals_status ON proposals(status);
      CREATE INDEX IF NOT EXISTS idx_proposals_workflow_id ON proposals(workflow_id);
      CREATE INDEX IF NOT EXISTS idx_proposals_idempotency_key ON proposals(idempotency_key);
    `);
  }

  /** Persist a freshly generated proposal at status `pending`. */
  create(p: GeneratedProposal): ProposalRecord {
    const now = nowIso();
    const result = this.db
      .prepare(
        `INSERT INTO proposals
           (workflow_id, state_id, targets, confidence_score, evidence_cluster,
            failure_count, version, idempotency_key, status, revisions, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', '[]', ?, ?)`,
      )
      .run(
        p.workflowId,
        p.stateId,
        JSON.stringify(p.targets),
        p.confidenceScore,
        JSON.stringify(p.evidenceCluster),
        p.failureCount,
        p.version,
        p.idempotencyKey,
        now,
        now,
      );
    const id = Number(result.lastInsertRowid);
    log.info(
      `proposal created: id=${id} workflow=${p.workflowId} state=${p.stateId} key=${p.idempotencyKey.slice(0, 12)}`,
    );
    return this.get(id)!;
  }

  /** Fetch one proposal by id, or null if it does not exist. */
  get(id: number): ProposalRecord | null {
    const row = this.db
      .prepare(`SELECT * FROM proposals WHERE id = ?`)
      .get(id) as Record<string, unknown> | undefined;
    return row ? rowToRecord(row) : null;
  }

  /**
   * Query proposals, optionally filtered by status and/or workflow. Newest
   * first. `limit` is clamped to a sane maximum.
   */
  query(q: { status?: ProposalStatus; workflowId?: string; limit?: number } = {}): ProposalRecord[] {
    const clauses: string[] = [];
    const params: unknown[] = [];

    if (q.status !== undefined) {
      clauses.push("status = ?");
      params.push(q.status);
    }
    if (q.workflowId !== undefined) {
      clauses.push("workflow_id = ?");
      params.push(q.workflowId);
    }

    const where = clauses.length ? `WHERE ${clauses.join(" AND ")}` : "";
    const rawLimit = q.limit;
    const limit =
      typeof rawLimit === "number" && Number.isFinite(rawLimit) && rawLimit > 0
        ? Math.min(rawLimit, 1000)
        : 100;

    const rows = this.db
      .prepare(`SELECT * FROM proposals ${where} ORDER BY created_at DESC, id DESC LIMIT ?`)
      .all(...params, limit) as Record<string, unknown>[];
    return rows.map(rowToRecord);
  }

  /** Transition a proposal to a new status. Rejects any value outside the enum. */
  setStatus(id: number, status: ProposalStatus): ProposalRecord {
    if (!isProposalStatus(status)) {
      throw new Error(`invalid proposal status: ${String(status)}`);
    }
    const existing = this.get(id);
    if (!existing) throw new Error(`proposal not found: ${id}`);

    this.db
      .prepare(`UPDATE proposals SET status = ?, updated_at = ? WHERE id = ?`)
      .run(status, nowIso(), id);
    return this.get(id)!;
  }

  /**
   * Revise a proposal IN PLACE (AC3.4). The superseded version's targets and the
   * operator feedback that superseded it are appended to the immutable revision
   * thread; the record then advances to the regenerated targets, bumps its
   * version and moves to `in-revision`. The same row is mutated — no new row.
   */
  revise(id: number, feedback: string, regenerated: GeneratedProposal): ProposalRecord {
    if (typeof feedback !== "string" || feedback.trim().length === 0) {
      throw new Error("revision requires operator feedback");
    }
    const current = this.get(id);
    if (!current) throw new Error(`proposal not found: ${id}`);

    // Preserve the version being superseded at the head of the immutable thread.
    const supersededEntry: ProposalRevision = {
      version: current.version,
      feedback,
      targets: current.targets,
      idempotencyKey: current.idempotencyKey,
      createdAt: nowIso(),
    };
    const revisions = [...current.revisions, supersededEntry];

    this.db
      .prepare(
        `UPDATE proposals
            SET targets = ?, confidence_score = ?, evidence_cluster = ?,
                failure_count = ?, version = ?, idempotency_key = ?,
                status = 'in-revision', revisions = ?, updated_at = ?
          WHERE id = ?`,
      )
      .run(
        JSON.stringify(regenerated.targets),
        regenerated.confidenceScore,
        JSON.stringify(regenerated.evidenceCluster),
        regenerated.failureCount,
        regenerated.version,
        regenerated.idempotencyKey,
        JSON.stringify(revisions),
        nowIso(),
        id,
      );
    log.info(`proposal revised: id=${id} → v${regenerated.version} (in-revision)`);
    return this.get(id)!;
  }

  close(): void {
    this.db.close();
  }
}

/** Re-exported so callers have one import for the store and its key derivation. */
export const computeIdempotencyKey = _computeIdempotencyKey;

function nowIso(): string {
  return new Date().toISOString();
}

function rowToRecord(row: Record<string, unknown>): ProposalRecord {
  return {
    id: Number(row.id),
    workflowId: String(row.workflow_id),
    stateId: String(row.state_id),
    targets: JSON.parse(String(row.targets)) as ProposalTarget[],
    confidenceScore: Number(row.confidence_score),
    evidenceCluster: JSON.parse(String(row.evidence_cluster)) as {
      ticketIds: string[];
      counts: Record<string, number>;
    },
    failureCount: Number(row.failure_count),
    version: Number(row.version),
    idempotencyKey: String(row.idempotency_key),
    status: String(row.status) as ProposalStatus,
    createdAt: String(row.created_at),
    updatedAt: String(row.updated_at),
    revisions: JSON.parse(String(row.revisions)) as ProposalRevision[],
  };
}
