/**
 * AI-2070 (P4-C3) — the prod trigger fires the deterministic generation engine
 * into the unified C4 store, end to end.
 *
 * These are the RED tests for the write-tests state. They fail on current `main`
 * because the distillation cron's `runDistillation` still emits `skill_workshop`
 * proposals over the gateway `/tools/invoke` HTTP API (`invokeGatewayTool`) and
 * never touches the deterministic engine (`generateProposals`) or the unified C4
 * store (`../store/proposal-store.ts`). Nothing generated by the prod trigger
 * therefore shows up in `GET /admin/api/proposals`.
 *
 * Contract the implementer conforms to (Igor's 17:50 map): the prod trigger —
 * `runDistillation` — gains the collaborators it now needs and, per run, must
 *   1. read threshold-crossing metrics from the ObservationStore,
 *   2. bridge them to `FailureCluster`s (MetricRow.tickets → ticketIds),
 *   3. call `generateProposals(clusters, ctx)` (the deterministic engine), and
 *   4. persist via `persistGeneratedProposals(proposalStore, generated)` into the
 *      unified C4 store the running app wires — NOT the legacy skill_workshop path.
 *
 * The new trigger signature this suite pins:
 *
 *   runDistillation(
 *     observationStore: ObservationStore,
 *     proposalStore: GeneratedProposalSink,   // the C4 ../store/proposal-store.ts
 *     ctx: GenerationContext,                  // prod readSurfaces
 *     options?: { threshold?: number },
 *   ): Promise<DistillationResult>
 *
 * There is NO DI-injected fake store: the proposal is written into, and read back
 * out of, the REAL `ProposalStore` the admin routes hold (`createApp(...)
 * .proposalStore`), driven through the actual `GET /admin/api/proposals` surface.
 * The test path NEVER calls `persistGeneratedProposals` — only the prod trigger does.
 */
import { describe, it, expect, beforeEach, afterEach, jest } from "@jest/globals";
import request from "supertest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { createApp } from "../index.js";
import { reloadAgents } from "../agents.js";
import { runDistillation } from "./p4-metrics-distillation.js";
import {
  generateProposals,
  type FailureCluster,
  type GenerationContext,
} from "../proposal/proposal-generator.js";

const ADMIN_SECRET = "ai2070-admin-secret";

/** The (workflow, step) whose recurring failures the trigger must distil. */
const WORKFLOW = "dev-impl";
const STEP = "code-review";
const REASON = "missing-tests";
const guidanceRel = path.join("workflows", WORKFLOW, `${STEP}.md`);

describe("AI-2070 — prod trigger → deterministic engine → unified C4 store → console queue", () => {
  let dir: string;
  let configRoot: string;
  let appState: ReturnType<typeof createApp>;
  let ctx: GenerationContext;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "ai2070-trigger-"));

    // Admin console static assets + empty agents roster (createApp needs both).
    const webDist = path.join(dir, "web-dist");
    fs.mkdirSync(webDist, { recursive: true });
    fs.writeFileSync(path.join(webDist, "index.html"), '<!doctype html><div id="root"></div>', "utf8");
    const agentsFile = path.join(dir, "agents.json");
    fs.writeFileSync(agentsFile, JSON.stringify({ agents: [] }), "utf8");

    // A real on-disk editable surface for the (workflow, step) under test, so the
    // generator has a non-empty surface and emits a proposal.
    configRoot = path.join(dir, "config");
    fs.mkdirSync(path.join(configRoot, "workflows", WORKFLOW), { recursive: true });
    fs.writeFileSync(
      path.join(configRoot, guidanceRel),
      `# ${STEP}\n\nReview the diff for correctness and reuse before approving.\n`,
      "utf8",
    );

    process.env.AGENTS_FILE = agentsFile;
    process.env.ADMIN_SECRET = ADMIN_SECRET;
    process.env.ADMIN_WEB_DIST = webDist;
    process.env.LINEAR_CONNECTOR_CONFIG_DIR = configRoot;
    reloadAgents();

    appState = createApp({
      proposalsDbPath: path.join(dir, "proposals.db"),
      bagDbPath: path.join(dir, "bag.db"),
      agentQueueDbPath: path.join(dir, "queue.db"),
      operationalEventsDbPath: path.join(dir, "opevents.db"),
      observationsDbPath: path.join(dir, "obs.db"),
    });

    // The prod readSurfaces returns the ACTUAL on-disk guidance bytes for the
    // (workflow, step) under test, and an empty array for anything else (empty ⇒
    // cluster skipped). This is the shape the implementer's prod ctx must produce.
    ctx = {
      readSurfaces: (workflowId, stateId) => {
        if (workflowId !== WORKFLOW || stateId !== STEP) return [];
        return [
          {
            kind: "guidance",
            path: guidanceRel,
            content: fs.readFileSync(path.join(configRoot, guidanceRel), "utf8"),
          },
        ];
      },
    };
  });

  afterEach(() => {
    delete process.env.AGENTS_FILE;
    delete process.env.ADMIN_SECRET;
    delete process.env.ADMIN_WEB_DIST;
    delete process.env.LINEAR_CONNECTOR_CONFIG_DIR;
    fs.rmSync(dir, { recursive: true, force: true });
  });

  /** Seed `n` reject observations for the group under test (distinct tickets). */
  function seedCrossingObservations(n: number): void {
    for (let i = 0; i < n; i++) {
      appState.observationStore.append({
        ticket: `AI-90${i}`,
        workflow: WORKFLOW,
        step: STEP,
        fromBody: "review body",
        reviewerBody: "missing tests for the new branch",
        reasonCode: REASON,
      });
    }
  }

  /** The key the deterministic engine derives for the seeded group (pure fn). */
  function expectedIdempotencyKey(count: number): string {
    const cluster: FailureCluster = {
      workflow: WORKFLOW,
      step: STEP,
      reasonCode: REASON,
      count,
      exceedsThreshold: true,
      ticketIds: [],
    };
    const [generated] = generateProposals([cluster], ctx);
    return generated.idempotencyKey;
  }

  // ── AC3 (headline) + AC2 ───────────────────────────────────────────────────
  // "End-to-end: trigger fires → proposal in console queue (no manual
  //  persistGeneratedProposals call in the test path)."
  // "Generated proposals land in the unified C4 store and appear in
  //  GET /admin/api/proposals."
  it("driving runDistillation on seeded threshold-crossing observations lands a generated proposal in the console queue", async () => {
    seedCrossingObservations(5);
    const key = expectedIdempotencyKey(5);

    // The prod trigger — NOT a manual persistGeneratedProposals call.
    await runDistillation(appState.observationStore, appState.proposalStore, ctx, { threshold: 3 });

    // Appears in the C5 console queue (GET /admin/api/proposals).
    const listRes = await request(appState.app)
      .get("/admin/api/proposals")
      .set("x-admin-secret", ADMIN_SECRET);
    expect(listRes.status).toBe(200);
    const proposals = listRes.body.proposals as Array<{ id: string; proposal: { targets: Array<{ path: string; kind: string }> } | null }>;
    const row = proposals.find((p) => p.id === key);
    expect(row).toBeDefined();
    // It is the bridged deterministic proposal (targets carry the guidance surface).
    expect(row?.proposal?.targets?.[0]?.path).toBe(guidanceRel);
    expect(row?.proposal?.targets?.[0]?.kind).toBe("guidance");

    // And it is readable by idempotency key (the apply-pipeline lookup, AC2).
    const byKey = appState.proposalStore.getByIdempotencyKey(key);
    expect(byKey).not.toBeNull();
    expect(byKey?.idempotencyKey).toBe(key);
  });

  // ── AC2 / Igor item 2: bridged, NOT the legacy skill_workshop gateway path ──
  it("routes generation through the deterministic engine + adapter, not the gateway skill_workshop path", async () => {
    seedCrossingObservations(4);

    const fetchSpy = jest.spyOn(globalThis, "fetch");
    try {
      await runDistillation(appState.observationStore, appState.proposalStore, ctx, { threshold: 3 });
    } finally {
      fetchSpy.mockRestore();
    }

    // The legacy path POSTs to the gateway `/tools/invoke` (skill_workshop). The
    // unified path persists straight into the store — no gateway round-trip.
    const hitGateway = fetchSpy.mock.calls.some((c) => {
      const url = typeof c[0] === "string" ? c[0] : (c[0] as URL | Request).toString();
      return url.includes("/tools/invoke");
    });
    expect(hitGateway).toBe(false);

    // The proposal that landed is the deterministic one, keyed by idempotency key.
    const key = expectedIdempotencyKey(4);
    expect(appState.proposalStore.getById(key)).not.toBeNull();
  });

  // ── Boundary: sub-threshold clusters yield no proposal ──────────────────────
  it("does not enqueue a proposal when no pattern crosses the threshold", async () => {
    seedCrossingObservations(2); // count 2 < threshold 3

    await runDistillation(appState.observationStore, appState.proposalStore, ctx, { threshold: 3 });

    const listRes = await request(appState.app)
      .get("/admin/api/proposals")
      .set("x-admin-secret", ADMIN_SECRET);
    expect(listRes.status).toBe(200);
    expect((listRes.body.proposals as unknown[]).length).toBe(0);
  });
});
