/**
 * Phase 4 / P4-3 — Periodic distillation of reject metrics into skill-workshop proposals.
 *
 * Scheduled job that:
 * 1. Reads P4-2 metric aggregation from ObservationStore
 * 2. Detects (workflow, step, reason_code) patterns exceeding threshold
 * 3. Emits a pending skill-workshop proposal for each crossing pattern (deduplicated)
 * 4. Follows existing propose → review → apply flow (pending by default)
 *
 * Design: design.md §8 (learning loop), §8.2 (system-level fix), §8.3 (propose → review → apply)
 */

import type { ObservationStore } from "../store/observation-store.js";
import { UNCLASSIFIED_REASON_CODE } from "../store/observation-store.js";
import { createLogger, componentLogger } from "../logger.js";
import { registerCron, markCronRun, formatIntervalMs } from "./registry.js";

const log = componentLogger(createLogger(process.env.LOG_LEVEL ?? "info"), "p4-metrics-distillation");

const DEFAULT_THRESHOLD = parseInt(process.env.P4_DISTILL_THRESHOLD ?? "3", 10);
const MAX_PROPOSALS_PER_RUN = parseInt(process.env.MAX_PROPOSALS_PER_RUN ?? "10", 10);
const DEFAULT_INTERVAL_MS = parseIntervalMs(process.env.P4_DISTILL_INTERVAL ?? "1h");

/** Registry key — shared by the registrar and the post-run liveness stamp. */
const DISTILLATION_CRON_NAME = "p4-metrics-distillation";

export interface DistillationResult {
  proposalsCreated: number;
  patternsCrossed: number;
  skipped: { pattern: string; reason: string }[];
  error?: string;
}

/** Parse a duration string like "1h", "30m", "3600s" or raw milliseconds. */
function parseIntervalMs(value: string): number {
  const trimmed = value.trim();
  if (/^\d+$/.test(trimmed)) return parseInt(trimmed, 10);
  const match = trimmed.match(/^(\d+(?:\.\d+)?)(ms|s|m|h|d)$/);
  if (!match) return 60 * 60 * 1000; // default 1h
  const n = parseFloat(match[1]);
  switch (match[2]) {
    case "ms": return n;
    case "s":  return n * 1_000;
    case "m":  return n * 60_000;
    case "h":  return n * 3_600_000;
    case "d":  return n * 86_400_000;
    default:   return 3_600_000;
  }
}

/** Call a tool via the OpenClaw gateway /tools/invoke HTTP API. */
async function invokeGatewayTool(tool: string, args: Record<string, unknown>): Promise<unknown> {
  const gatewayUrl = (process.env.OPENCLAW_GATEWAY_URL ?? "http://localhost:18789").replace(/\/$/, "");
  const token = process.env.OPENCLAW_GATEWAY_TOKEN ?? process.env.OPENCLAW_GATEWAY_PASSWORD;

  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (token) headers["Authorization"] = `Bearer ${token}`;

  const response = await fetch(`${gatewayUrl}/tools/invoke`, {
    method: "POST",
    headers,
    body: JSON.stringify({ tool, args }),
  });

  const data = await response.json() as { ok: boolean; result?: unknown; error?: { message?: string } };
  if (!data.ok) {
    throw new Error(data.error?.message ?? `Gateway tool invoke failed (status ${response.status})`);
  }
  return data.result;
}

/** Check if a pending skill-workshop proposal already exists for the given name. */
async function proposalExists(name: string): Promise<boolean> {
  try {
    const result = await invokeGatewayTool("skill_workshop", { action: "list" }) as { proposals?: Array<{ name: string; status?: string }> } | null;
    if (!result || !Array.isArray((result as { proposals?: unknown[] }).proposals)) return false;
    const proposals = (result as { proposals: Array<{ name: string; status?: string }> }).proposals;
    return proposals.some(
      (p) => p.name === name && (!p.status || p.status === "pending")
    );
  } catch (err) {
    log.warn(`[P4-3] Could not check for existing proposals: ${err instanceof Error ? err.message : String(err)} — skipping dedup check`);
    return false;
  }
}

function buildProposalContent(workflow: string, step: string, reasonCode: string, count: number, description: string): string {
  return [
    `# Skill: ${workflow}-${step}-${reasonCode}`,
    "",
    description,
    "",
    "## Steps",
    "",
    `1. Add ${reasonCode} checklist items to the ${step} step`,
    "2. Update step documentation",
    "3. Train on common pitfalls",
    "",
    "## Acceptance Criteria",
    "",
    `- [ ] ${reasonCode} checklist added to ${step}`,
    "- [ ] Step documentation updated",
    "- [ ] Reviewer guidelines updated",
    "",
    `_Auto-generated by P4-3 distillation. Pattern: ${workflow}/${step}/${reasonCode} crossed threshold (count=${count})._`,
  ].join("\n");
}

function buildDescription(workflow: string, step: string, reasonCode: string, count: number): string {
  const reasonLabels: Record<string, string> = {
    "missing-tests": "missing tests",
    "style": "code style issues",
    "scope-creep": "scope creep",
    "correctness": "correctness issues",
    "ac-mismatch": "AC mismatch",
  };
  const label = reasonLabels[reasonCode] ?? `"${reasonCode}"`;
  const desc = `${workflow}/${step}: ${label} rejected ${count}× — add checklist + update docs`;
  return desc.length <= 160 ? desc : desc.slice(0, 157) + "...";
}

/**
 * Run P4-3 distillation: scan metrics and create proposals for threshold-crossing patterns.
 */
export async function runDistillation(observationStore: ObservationStore, threshold?: number): Promise<DistillationResult> {
  const actualThreshold = threshold ?? DEFAULT_THRESHOLD;

  try {
    log.info(`[P4-3] Running distillation with threshold=${actualThreshold}`);

    const metrics = observationStore.metrics({ threshold: actualThreshold });
    const crossedPatterns = metrics.items.filter((item) => item.exceedsThreshold);

    // AI-2036: `unclassified` means the reviewer named no category. It clusters
    // like any other code, but there is no lesson to distil from "we don't know
    // why" — a proposal saying `unclassified rejected 3× — add checklist` is
    // noise. Count it, surface it, never propose from it. Before AI-2036 the
    // table was empty, so this path had never run against real data.
    const proposable = crossedPatterns.filter((item) => item.reasonCode !== UNCLASSIFIED_REASON_CODE);
    const uncategorized = crossedPatterns.length - proposable.length;

    log.info(
      `[P4-3] Found ${crossedPatterns.length} crossed pattern(s)` +
        (uncategorized > 0 ? ` — ${uncategorized} uncategorized, not proposable` : ""),
    );

    const candidates = proposable.slice(0, MAX_PROPOSALS_PER_RUN).map((item) => ({
      workflow: item.workflow,
      step: item.step,
      reasonCode: item.reasonCode,
      count: item.count,
      name: `${item.workflow}-${item.step}-${item.reasonCode}`,
    }));

    let proposalsCreated = 0;
    const skipped: { pattern: string; reason: string }[] = [];

    for (const candidate of candidates) {
      const patternLabel = `${candidate.workflow}/${candidate.step}/${candidate.reasonCode}`;
      try {
        const exists = await proposalExists(candidate.name);
        if (exists) {
          log.info(`[P4-3] Skipping ${patternLabel} — pending proposal already exists`);
          skipped.push({ pattern: patternLabel, reason: "existing-pending-proposal" });
          continue;
        }

        const description = buildDescription(candidate.workflow, candidate.step, candidate.reasonCode, candidate.count);
        const proposalContent = buildProposalContent(candidate.workflow, candidate.step, candidate.reasonCode, candidate.count, description);

        await invokeGatewayTool("skill_workshop", {
          action: "create",
          name: candidate.name,
          description,
          proposal_content: proposalContent,
        });

        log.info(`[P4-3] Created proposal: ${candidate.name} (count=${candidate.count})`);
        proposalsCreated++;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log.error(`[P4-3] Failed to create proposal for ${patternLabel}: ${msg}`);
        skipped.push({ pattern: patternLabel, reason: "proposal-creation-failed" });
      }
    }

    log.info(`[P4-3] Distillation complete: ${proposalsCreated} created, ${skipped.length} skipped`);

    return { proposalsCreated, patternsCrossed: crossedPatterns.length, skipped };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    log.error(`[P4-3] Distillation failed: ${errorMessage}`);
    return { proposalsCreated: 0, patternsCrossed: 0, skipped: [], error: errorMessage };
  }
}

/**
 * Register the P4-3 distillation as an in-process recurring job.
 * Interval is controlled by P4_DISTILL_INTERVAL env var (default: 1h).
 * The timer is unref'd so it won't prevent graceful shutdown.
 */
export function registerDistillationCron(observationStore: ObservationStore): void {
  const intervalMs = DEFAULT_INTERVAL_MS;
  registerCron(DISTILLATION_CRON_NAME, `every ${formatIntervalMs(intervalMs)}`);
  const timer = setInterval(() => {
    runDistillation(observationStore)
      .then(() => markCronRun(DISTILLATION_CRON_NAME))
      .catch((err) => {
        log.error(`[P4-3] Scheduled distillation failed: ${err instanceof Error ? err.message : String(err)}`);
      });
  }, intervalMs);
  timer.unref();
  log.info(`[P4-3] Distillation scheduled every ${intervalMs}ms (P4_DISTILL_INTERVAL=${process.env.P4_DISTILL_INTERVAL ?? "1h"})`);
}
